#!/bin/bash
vmlist=$1
typenum=$2

totalcount=$(($typenum+2))
index=0

#prep headnode
cp -r /share/home/hpcuser/.ssh /root/

echo "the first vm is ${vmlist[0]}"

#needs to be done sequentially
for vmname in ${vmlist[@]}; do
	if [ $index -lt $totalcount ] ; then
	echo "Rebooting $vmname"
	ssh hpcuser@${vmname} "sudo reboot 2>/dev/null; exit 2>/dev/null" 2>/dev/null || :
        fi
done
exit 0
