pr: none
schedules:
- cron: "0 0 * * Sun"
  displayName: Every Sunday midnight build
  branches:
    include:
    - master
  always: true

trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    include:
      - examples/simple_hpc_pbs/*
      - pyazhpc/*
      - scripts/create_raid0.sh
      - scripts/make_filesystem.sh
      - scripts/node_healthchecks.sh
      - scripts/install-nfsserver.sh
      - scripts/nfsclient.sh
      - scripts/localuser.sh
      - scripts/pbsdownload.sh
      - scripts/pbsserver.sh
      - scripts/pbsclient.sh
    exclude:
      - examples/simple_hpc_pbs/readme.md

pool: Default

variables:
  - group: azhpc_build_common
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  # configuration file to use
  - name: azhpc.config
    value: examples/simple_hpc_pbs/config.json
  # pipeline directory
  - name: azhpc.pipeline_dir
    value: examples/simple_hpc_pbs
  # destination of scripts. Default is hpcuser@headnode:/apps
  #azhpc.script_remote_dest: 'hpcadmin@jumpbox:.'

# Add the variables needed in your configuration file
# Set values below or thru pipeline variables
  # - name: azhpc.variables.variable_name
  #   value: variable_value

# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

jobs:
- template: ../../ci/templates/jobs/build.yml
  parameters:
    extra_steps: ../../../examples/simple_hpc_pbs/test.yml
