apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-problem-detector
  namespace: kube-system
  labels:
    app: node-problem-detector
spec:
  selector:
    matchLabels:
      app: node-problem-detector
  template:
    metadata:
      labels:
        app: node-problem-detector
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
                  - key: accelerator
                    operator: In
                    values:
                      - nvidia
      containers:
      - name: node-problem-detector
        command:
        - /node-problem-detector
        - --logtostderr
        - --config.custom-plugin-monitor=/config/custom-plugin-gpu-count.json,/config/custom-plugin-gpu-nvlink.json,/config/custom-plugin-gpu-xid.json
        image: <YOUR ACR>.azurecr.io/k8s-staging-npd/node-problem-detector:<YOUR TAG>
        resources:
          limits:
            cpu: 240m
            memory: 2048Mi
          requests:
            cpu: 240m
            memory: 2048Mi
        imagePullPolicy: Always
        securityContext:
          privileged: true
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: log
          mountPath: /var/log
          readOnly: true
        - name: kmsg
          mountPath: /dev/kmsg
          readOnly: true
        # Make sure node problem detector is in the same timezone
        # with the host.
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
        - name: config
          mountPath: /config
          readOnly: true
      serviceAccountName: node-problem-detector
      volumes:
      - name: log
        # Config `log` to your system log directory
        hostPath:
          path: /var/log/
      - name: kmsg
        hostPath:
          path: /dev/kmsg
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: config
        configMap:
          name: node-problem-detector-config
          defaultMode: 0777
          items:
          - key: kernel-monitor.json
            path: kernel-monitor.json
          - key: docker-monitor.json
            path: docker-monitor.json
          - key: custom-plugin-monitor.json
            path: custom-plugin-monitor.json
          - key: check_ntp.sh
            path: plugin/check_ntp.sh
          - key: custom-plugin-gpu-count.json
            path: custom-plugin-gpu-count.json
          - key: check_gpu_count.sh
            path: plugin/check_gpu_count.sh
          - key: custom-plugin-gpu-nvlink.json
            path: custom-plugin-gpu-nvlink.json
          - key: check_gpu_nvlink.sh
            path: plugin/check_gpu_nvlink.sh
          - key: custom-plugin-gpu-xid.json
            path: custom-plugin-gpu-xid.json
          - key: check_gpu_xid.sh
            path: plugin/check_gpu_xid.sh
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
