#!/bin/bash
#
# Relevant PBS variables (qsub -v option)
#
# SKU_TYPE = hb, hc or hbv2
# INPUTDIR, location of namd input files.

export MODULEPATH=/apps/modulefiles/${SKU_TYPE}:$MODULEPATH

module load mpi/openmpi
spack load fftw@3
module load NAMD/2.14-openmpi

cat $PBS_NODEFILE

NPROCS=`cat $PBS_NODEFILE | wc -l`
cd $PBS_O_WORKDIR
cp ${INPUTDIR}/* .

#mpirun -x LD_LIBRARY_PATH -n $NPROCS --hostfile $PBS_NODEFILE --bind-to numa `which namd2` +isomalloc_sync *.namd
mpirun -x LD_LIBRARY_PATH -n $NPROCS --hostfile $PBS_NODEFILE `which namd2` +isomalloc_sync *.namd
