#!/bin/bash

FILESYSTEM=${FILESYSTEM:-/beegfs/datafiles}

source /etc/profile
set -euo pipefail  # better error handling

export NPROCS=`cat $PBS_NODEFILE | wc -l`

export MODULEPATH=/apps/modulefiles:$MODULEPATH
module load io500-app
module load gcc-9.2.0
module load mpi/openmpi

cat $PBS_O_WORKDIR

cd $PBS_O_WORKDIR
sed -i "s#^datadir.*#datadir = ${FILESYSTEM}#" ./config-io500.ini
mpirun -n $NPROCS --hostfile $PBS_NODEFILE `which io500` config-io500.ini
