pr: none
schedules:
- cron: "0 0 * * Sun"
  displayName: Every Sunday midnight build
  branches:
    include:
    - master
  always: true

trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    include:
      - examples/cc_anf/*
      - blocks/cycle-install-server-managed-identity.json
      - blocks/cycle-prereqs-managed-identity.json
      - blocks/cycle-cli-local.json
      - blocks/cycle-cli-jumpbox.json
      - blocks/jumpbox-anf.json
      - blocks/vnet.json
      - blocks/anf.json
    exclude:
      - examples/cc_anf/readme.md

pool: Default

variables:
  - group: azhpc_build_common
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  # configuration file to use
  - name: azhpc.config
    value: examples/cc_anf/variables.json
  # pipeline directory
  - name: azhpc.pipeline_dir
    value: examples/cc_anf
  # destination of scripts. Default is hpcuser@headnode:/apps
  - name: azhpc.script_remote_dest
    value: 'hpcadmin@jumpbox:.'

# Add the variables needed in your configuration file
# Set values below or thru pipeline variables
  # - name: azhpc.variables.variable_name
  #   value: variable_value

# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

jobs:
- template: ../../ci/templates/jobs/build.yml
  parameters:
    pre_steps: ../../../examples/cc_anf/init.yml
    extra_steps: ../../../examples/cc_anf/test.yml