pr: none
schedules:
- cron: "0 0 * * Sun"
  displayName: Every Sunday midnight build
  branches:
    include:
    - master
  always: true

trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    include:
      - examples/cycleserver_msi/*
      - blocks/cycle-install-server-managed-identity.json
      - blocks/cycle-prereqs-managed-identity.json
      - blocks/cycle-cli-local.json
      - blocks/cycle-cli-jumpbox.json
      - blocks/jumpbox-nfs.json.json
      - blocks/vnet.json
      - scripts/cc_install_managed_identity.sh
    exclude:
      - examples/cycleserver_msi/readme.md

pool: Default

variables:
  - group: azhpc_build_common
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
  # configuration file to use
  - name: azhpc.config
    value: examples/cycleserver_msi/variables.json
  # pipeline directory
  - name: azhpc.pipeline_dir
    value: examples/cycleserver_msi
  # destination of scripts. Default is hpcuser@headnode:/apps
  - name: azhpc.script_remote_dest
    value: 'hpcadmin@jumpbox:.'

  - name: azhpc.variables_matrix
    value: examples/cycleserver_msi/test_matrix.json
# Add the variables needed in your configuration file
# Set values below or thru pipeline variables
  # - name: azhpc.variables.variable_name
  #   value: variable_value

# <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

jobs:
- template: ../../ci/templates/jobs/build.yml
  parameters:
    pre_steps: ../../../examples/cycleserver_msi/init.yml
