#!/bin/bash
#
OUTDIR=${OUTDIR:-/data/osu_ring_bw_hpcx}
if [ ! -d $OUTDIR ]; then
   mkdir -p $OUTDIR
fi
cd $OUTDIR

module load gcc-9.2.0
module load mpi/hpcx

src=$(tail -n1 $PBS_NODEFILE)
dst=$(head -n1 $PBS_NODEFILE)
mpirun -np 2 --host $src,$dst --map-by node $HPCX_OSU_DIR/osu_latency | tee ${src}_to_${dst}_osu_latency.log_$$
mpirun -np 2 --host $src,$dst --map-by node $HPCX_OSU_DIR/osu_bibw | tee ${src}_to_${dst}_osu_bw.log_$$
