#!/bin/bash

SHARED_APPS=/apps

export MODULEPATH=${SHARED_APPS}/modulefiles/spack/tcl/hb/linux-centos7-x86_64:$MODULEPATH
module load gcc-8.2.0
module load mpi/mpich-3.3
spack load osu-micro-benchmarks^mpich

cat $PBS_NODEFILE

PKEY=$(grep -v -e 0000 -e 0x7fff --no-filename /sys/class/infiniband/mlx5_0/ports/1/pkeys/*)
PKEY=${PKEY/0x8/0x0}

mpirun -bind-to hwthread  -env UCX_IB_PKEY=$PKEY -env UCX_NET_DEVICES=mlx5_0:1 -env MPIR_CVAR_ENABLE_HCOLL=1 osu_latency
