#!/bin/bash

SHARED_APPS=/apps

module use /apps/modulefiles
module load spack/spack
source $SPACK_SETUP_ENV

module load mpi/hpcx
spack load osu-micro-benchmarks^hpcx

cat $PBS_NODEFILE

cd $PBS_O_WORKDIR

mpirun -x PATH --hostfile $PBS_NODEFILE --map-by ppr:1:node --bind-to core --report-bindings osu_bw
sleep 2
mpirun -x PATH --hostfile $PBS_NODEFILE --map-by ppr:1:node --bind-to core --report-bindings osu_latency
