#!/bin/bash

SHARED_APPS=/apps

export OMP_NUM_THREADS=1

module load gcc-9.2.0
module load mpi/hpcx-v2.5.0
spack load osu-micro-benchmarks^hpcx

cat $PBS_NODEFILE

cd $PBS_O_WORKDIR
sed -e 's/$/ slots=1/' $PBS_NODEFILE > hpcx_hostfile

mpirun -x PATH --hostfile hpcx_hostfile --map-by core --report-bindings --mca pml ucx osu_bw
sleep 2
mpirun -x PATH --hostfile hpcx_hostfile --map-by core --report-bindings --mca pml ucx osu_latency
